### ISSUE TITLE
Question : How to save big array (more than 8k)

### ISSUE THREAD

**Issue by Vdauphin** [code34/inidbi2#2]
Hello, I have a little question. 
Actually, the mission https://github.com/Giallustio/HeartsAndMinds is saved by using profileNamespace. We want to migrate to iniDB.
Actually, each city have a dedicate array with many different information store (like : units position, vehicle , behavior, IED position, can be STRING, NUMBER, ARRAY type...). After, we create an array of city : [city1,city2,city3] and I save it in a key "cities" like :
- cities = "[city1,city2,city3]"

This array could be very big depending on random spawn scripts and reach the 8K limit sometimes.

To deal with it I had two approach :  
- 1 https://github.com/Vdauphin/HeartsAndMinds/pull/83: Take the array [city1,city2,city3] and check if the array is to big. If it is, I reduce the size of it and save separately the array in two keys ("cities1","cities2"):
  - cities1 = "[city1,city2]"
  - cities2 ="[city3]"
  
  The load phase is easy just read ("cities1","cities2") and `append` .
- 2 https://github.com/Vdauphin/HeartsAndMinds/pull/85 : The idea here is to create a string of array : "[city1,city2,city3]" . Next I divide this string in string of 8100 size and store each 8100 string in keys ("cities1","cities2","cities3") . Result : 
  - cities1=""[city1"" 
  - cities2="",cit""
  - cities3 = ""y2,city3] ""
  
  The load phase is done by reading ("cities1","cities2","cities3")  and do `cities1 + cities2 + cities3`.

Problems : 
- 1: this solution work but is not really obtimized because the script do a loop on the [city1,city2,city3] size and try to find subarray with size smaller than 8100.
- 2: this solution is more optimize because the script devide in string the [city1,city2,city3] array with the correct size without loop. But a problem appear when I load keys because if `city1=["Paris", 1789]` has a string, the stored variable looks like :
  - cities1=""[["Paris", 1789]""
  
  So when this data is loaded, cities1 looks like this `cities1="[["Paris", 1789]"` and trow an error because Arma/IniDB see a string `"[["` next to `Paris` next to `", 1789]"` and don't understand. Here an exemple of .rtp : 

```
21:03:03 Error in expression <ED","NO CHANGE","NO CHANGE","UNCHANGED"]]],[]],[0,[[5029.77,11248.3,0.481865]],[>
21:03:03   Error position: <]],[]],[0,[[5029.77,11248.3,0.481865]],[>
21:03:03   Error ; manquant
21:03:03 Error in expression <ED","NO CHANGE","NO CHANGE","UNCHANGED"]]],[]],[0,[[5029.77,11248.3,0.481865]],[>
21:03:03   Error position: <]],[]],[0,[[5029.77,11248.3,0.481865]],[>
21:03:03   Error ; manquant
21:03:03 Error in expression <y];
_result = call compile _result;

if(_result select 0) then {
_data = _result>
21:03:03   Error position: <_result select 0) then {
_data = _result>
21:03:03   Error Variable indéfinie dans une expression: _result
21:03:03 File inidbi2\oo_inidbi.sqf, line 169
```

I would like to know if there is any other solution/idea to deal with big array ? Or if the solution 2 can be fix by an other approach ?
May be solution 1 is the best in my case ?

Sorry for my English
Thx

**Comment by code34** [comment]
Hello :)
happy to see a nice project, looking for inidbi :)

Concerning the support of biggest array in indbi, it s currently in hold mode cause i m working currently on other things but i have to think about it.

Anyway the differents methods will consums ressources, cause it will require to use a little protocol exchange between dll & sqf, and will do somes loops to chunck the array in strings as you do in your last solution.
for you problem, to understand where it comes from, you can try this expression alone:

_testvariable = "[["Paris", 1789]";
and this one

_testvariable = "[['Paris', 1789]";

```
  De : Vdauphin <notifications@github.com>
```

 À : code34/inidbi2 inidbi2@noreply.github.com 
 Envoyé le : Jeudi 4 février 2016 0h31
 Objet : [inidbi2] Question : How to save big array (more than 8k) (#2)

Hello, 
I have a little question. Actually, the mission https://github.com/Giallustio/HeartsAndMinds is saved by using profileNamespace. We want to migrate to iniDB.
Actually, each city have a dedicate array with many different information store (like : units position, vehicle , behavior, IED position, can be STRING, NUMBER, ARRAY type...). After, we create an array of city : [city1,city2,city3] and I save it in a key "cities" like :   
- cities = "[city1,city2,city3]"
  This array could be very big depending on random spawn scripts and reach the 8K limit sometimes.To deal with it I had two approach :  
- 1: Take the array [city1,city2,city3] and check if the array is to big. If it is, I reduce the size of it and save separately the array in two keys ("cities1","cities2"):  
  - cities1 = "[city1,city2]"
  - cities2 ="[city3]"
    Vdauphin/HeartsAndMinds#83 . The load phase is easy just read ("cities1","cities2") and append .
- 2: The idea here is to create a string of array : "[city1,city2,city3]" . Next I divide this string in string of 8100 size and store each 8100 string in keys ("cities1","cities2","cities3") . Result :  
  - cities1=""[city1"" 
  - cities2="",cit""
  - cities3 = ""y2,city3] ""
    The load phase is done by reading ("cities1","cities2","cities3") and do cities1 + cities2 + cities3.
    Problems :  
- 1: this solution work but is not really obtimized because the script do a loop on the [city1,city2,city3] size and try to find subarray with size smaller than 8100.
- 2: this solution is more optimize because the script devide in string the [city1,city2,city3] array with the correct size without loop. But a problem appear when I load keys because if city1=["Paris", 1789] has a string, the stored variable looks like :  
  - cities1=""[["Paris", 1789]""

So when this data is loaded, cities1 looks like this cities1="[["Paris", 1789]" and trow an error because Arma/IniDB see a string "[[" next to Paris next to ", 1789]" and don't understand. Here an exemple of .rtp : 21:03:03 Error in expression <ED","NO CHANGE","NO CHANGE","UNCHANGED"]]],[]],[0,[[5029.77,11248.3,0.481865]],[>
21:03:03   Error position: <]],[]],[0,[[5029.77,11248.3,0.481865]],[>
21:03:03   Error ; manquant
21:03:03 Error in expression <ED","NO CHANGE","NO CHANGE","UNCHANGED"]]],[]],[0,[[5029.77,11248.3,0.481865]],[>
21:03:03   Error position: <]],[]],[0,[[5029.77,11248.3,0.481865]],[>
21:03:03   Error ; manquant
21:03:03 Error in expression <y];
_result = call compile _result;

if(_result select 0) then {
_data = _result>
21:03:03   Error position: <_result select 0) then {
_data = _result>
21:03:03   Error Variable indéfinie dans une expression: _result
21:03:03 File inidbi2\oo_inidbi.sqf, line 169
I would like to know if there is any other solution/idea to deal with big array ? Or if the solution 2 can be fix by an other approach ?
May be solution 1 is the best in my case ?Sorry for my English
Thx !!!—

**Comment by Vdauphin** [comment]
Hello !
Thx for your fast answer. 
I tested your _testvariable in "write" and "load" case and it works well !
The `call compile (a + "]")` return the correct array `[["Paris",1789]]` without issue.

Now I need to find the faster way to replace " by ' in string may be like : 

```
_Doublequotation_pos = _string_of_array find '"';
while {!(_Doublequotation_pos isEqualTo -1)} do {
    _string_of_array = (_string_of_array select [0, _Doublequotation_pos]) + "'" + (_string_of_array select [_Doublequotation_pos + 1, _size_array]);
    _Doublequotation_pos = _string_of_array find '"';
};
```

Thank you for your suggestion

**Comment by Vdauphin** [comment]
For the little story, I choosed the first solution because the replacement of " by ' with a lot of string in array is very computing expensive (ex: https://github.com/Vdauphin/HeartsAndMinds/pull/85#issuecomment-180879646).
